Added Search Function, Publish Option, Multiple File Uploads, Zenodo Token Requirement
NSLS-II/conda-pack-template pull request #17
Opened 2021-08-03 16:02 UTC by johngedell

2021-08-04 17:39 UTC, mrakitin reviewed
Looks good. I added a minor suggestion to fix the command to generate md5 checksum files.

2021-08-04 17:48 UTC, johngedell commented on zenodo_uploader.py
> +    search = search.replace("/", " ")  # zenodo can't handle '/' in search query
It breaks without the "/" symbol.

2021-08-04 20:27 UTC, mrakitin reviewed
This is almost ready. Just need a more advanced selection of the record of interest, rather than the first record from the search results. Otherwise looks good.

2021-08-04 20:27 UTC, mrakitin commented on zenodo_uploader.py
> +    deposition = records[0]
As we discussed over the call, instead of picking the first entry, we want to loop over the found records here, and filter by `owner` and `title`, and accumulate the information into a separate list. Then, we compare the dates when the uploading happened, and pick the latest one. @johngedell, could you please add this check here?

2021-08-05 03:42 UTC, johngedell commented on zenodo_uploader.py
> +    deposition = records[0]
Done.

2021-08-05 04:34 UTC, mrakitin reviewed
Thanks, @johngedell! That's exactly what we need/want. I suggested a few modifications, but we are on the right track with this development. And thanks for updating the PR description!

2021-08-05 04:34 UTC, mrakitin commented on zenodo_uploader.py
> +import hashlib
Not needed, not used anywhere.
```suggestion
```

2021-08-05 04:34 UTC, mrakitin commented on zenodo_uploader.py
> +    params = {"q": search, "sort": "mostrecent"}
👍, nice find about sorting.

2021-08-05 04:34 UTC, mrakitin commented on zenodo_uploader.py
> +    url = zenodo_server + "deposit/depositions?" + urlencode(params)
We use the style of f-strings here, so I suggest converting it to that:
```suggestion
    url = f"{zenodo_server}deposit/depositions?{urlencode(params)}"
```

2021-08-05 04:34 UTC, mrakitin commented on zenodo_uploader.py
> +    )[0]
When something like that is done, I suggest adding a sample of the `metadata` dictionary. That's what I have for one of the searches:
```py
In [36]: res[0].data['metadata']
Out[36]:
{'access_right': 'open',
 'access_right_category': 'success',
 'creators': [{'affiliation': 'BNL', 'name': 'Rakitin, Maksim'}],
 'description': '<p>Test&nbsp; data from NSLS-II CHX Eiger4</p>',
 'doi': '10.5072/zenodo.594668',
 'keywords': ['test, Eiger4M'],
 'license': {'id': 'CC-BY-4.0'},
 'publication_date': '2020-06-03',
 'related_identifiers': [{'identifier': '10.5072/zenodo.594667',
   'relation': 'isVersionOf',
   'scheme': 'doi'}],
 'relations': {'version': [{'count': 1,
    'index': 0,
    'is_last': True,
    'last_child': {'pid_type': 'recid', 'pid_value': '594668'},
    'parent': {'pid_type': 'recid', 'pid_value': '594667'}}]},
 'resource_type': {'title': 'Dataset', 'type': 'dataset'},
 'title': 'Test  data from NSLS-II CHX Eiger4'}
```

2021-08-05 04:34 UTC, mrakitin commented on zenodo_uploader.py
> +    print(f"Best match is deposition: {deposition['id']}")
We want more details:
```suggestion
    print(f"Best match is deposition: {deposition['id']}\n"
          f"Title: {deposition['metadata']['title']}\n"
          f"Publication date: {deposition['metadata']['publication_date']}\n")
```

2021-08-05 04:34 UTC, mrakitin commented on zenodo_uploader.py
> +        with open(f"{env_name}-md5sum.txt", "r") as fp:
This can be a quick workaround with the assumption the checksum file resides in the same location as the .tar.gz one.
```suggestion
        with open(f"{os.path.dirname(filename)}/{env_name}-md5sum.txt", "r") as fp:
```

2021-08-05 04:34 UTC, mrakitin commented on zenodo_uploader.py
> +        )
We should probably do the same check for `ZENODO_OWNER_ID`, so that it exits immediately if that var is not defined. Also, checking that it's integer would be useful, as someone can just specify their account name, which would not be right.

2021-08-05 04:34 UTC, mrakitin commented on zenodo_uploader.py
> +                )
This block is repeating. Can it be wrapped into a small helper function, and reused here and in the case above?

2021-08-05 04:37 UTC, johngedell commented on zenodo_uploader.py
> +    params = {"q": search, "sort": "mostrecent"}
Thanks.

2021-08-05 04:39 UTC, mrakitin commented on zenodo_uploader.py
> +    params = {"q": search, "sort": "mostrecent"}
Is it documented anywhere in Zenodo API docs?

2021-08-05 05:30 UTC, johngedell commented on zenodo_uploader.py
> +                )
Done.

2021-08-05 05:40 UTC, johngedell commented on zenodo_uploader.py
> +        )
Done.

2021-08-05 06:50 UTC, mrakitin commented on zenodo_uploader.py
> +            "Please create an environment variable with the token.\n"
```suggestion
            "Please create an environment variable with the owner ID.\n"
```

2021-08-05 07:05 UTC, johngedell commented on zenodo_uploader.py
> +    )[0]
Okay. I will look through this tomorrow.

2021-08-09 15:19 UTC, mrakitin commented on zenodo_uploader.py
> +    r = requests.put(update_url, data=json.dumps(f"{deposition['metadata']}"), headers=headers)
Should the token be passed here as well?

2021-08-09 15:22 UTC, mrakitin requested changes
Couple of comments regarding the latest additions to `Dockerfile.j2`.

2021-08-09 15:22 UTC, mrakitin commented on templates/Dockerfile.j2
> +{%- if extra_cmd_after_install %}{{ '\n' }}
This should be `extra_cmd_before_install`, not `extra_cmd_after_install`.

2021-08-09 15:22 UTC, mrakitin commented on templates/Dockerfile.j2
> +    conda create -p /opt/conda_envs/${env_name} ${channels} --override-channels -y python=${python_version} conda-pack ${pkg_name} ${extra_package>RUN bash -l -c "conda activate /opt/conda_envs/{{ en
I am concerned about the `>` symbol again. Please check #18 for the latest version of the template.

2021-08-11 17:10 UTC, mrakitin reviewed
I read through it and spotted a couple of places to improve. Please see my comments below.

2021-08-11 17:10 UTC, mrakitin commented on zenodo_uploader.py
> +    )[0]
Could you please add this sample dictionary in the comment block next to the code that deals with that? Thanks.

2021-08-11 17:11 UTC, mrakitin commented on templates/Dockerfile.j2
> +{%- if extra_cmd_after_install %}{{ '\n' }}
I resolved it within #18, which is made a part of this PR via rebasing on `main`.

2021-08-11 17:12 UTC, mrakitin commented on templates/Dockerfile.j2
> +    conda create -p /opt/conda_envs/${env_name} ${channels} --override-channels -y python=${python_version} conda-pack ${pkg_name} ${extra_package>RUN bash -l -c "conda activate /opt/conda_envs/{{ en
This is resolved after rebasing.

2021-08-11 17:13 UTC, mrakitin commented on zenodo_uploader.py
> +    r = requests.put(update_url, data=json.dumps(f"{deposition['metadata']}"), headers=headers)
Resolved after rebasing.

2021-08-12 16:45 UTC, merged