Adding runner.sh.j2 and zenodo_uploader.py files
NSLS-II/conda-pack-template pull request #9
Opened 2021-07-23 06:36 UTC by johngedell

2021-07-23 14:46 UTC, mrakitin requested changes
Thanks, @johngedell. I left a few suggestions and comments on how to tweak the code to be more ready for production (batch mode).

I'd expect the pull request body to contain some output of the scripts, and examples of application of the renderer with the config .yml files to generate the resulting `runner.sh` scripts. Can it be done?

Also, can you please demonstrate that this script could upload Docker images to all 3 places (quay, dockerhub, ghcr) and provide the resulting links?

Same would be great for Zenodo, at least using their sandbox website, but keeping in mind we need to eventually upload to their production site.

2021-07-23 14:46 UTC, mrakitin commented on runner.sh.j2
> +image="nsls2-analysis-2021-1.2"
This parameter and `env_name` below should come from the configs.

2021-07-23 14:46 UTC, mrakitin commented on runner.sh.j2
> +{% if -f "${image}.tar.gz" %}
These jinja conditions should be used for values based on config files, not the actual state during runtime. I suggest converting this condition to a normal bash `if`.

2021-07-23 14:46 UTC, mrakitin commented on zenodo_uploader.py
> +    )
For this file, could you please apply [`black`](https://pypi.org/project/black/) automated code formatting tool, and check also with [`flake8`](https://pypi.org/project/flake8/) and [`isort`](https://pypi.org/project/isort/)?

Also, I suggest wrapping the code above into a function and calling it later, such as:
```py
def upload_to_zenodo(...):
    ...

if __name__ == "__main__":
    res = upload_to_zenodo(<parameters>)
    print(res)
```
That way it'll be much easier in the future to convert it to an entry point, and import in other places.

2021-07-23 14:46 UTC, mrakitin commented on zenodo_uploader.py
> +ACCESS_TOKEN = input("Enter Access Token: ")
I suggest dealing with it via `os.getenv('ZENODO_ACCESS_TOKEN')`. We want to avoid interactive inputs as these tools will be running in a batch mode.

2021-07-23 14:46 UTC, mrakitin commented on zenodo_uploader.py
> +path = input("Enter file path as '/path/to/my-file.zip': ")
The names should be taken from the config files. Please avoid interactive input here too.

If the interactive input is needed, we can handle it via [`argparse`](https://docs.python.org/3/library/argparse.html), but I suggest we don't spend time on that _now_.

2021-07-23 14:46 UTC, mrakitin commented on zenodo_uploader.py
> +        "%s/%s" % (bucket_url, filename),
Python 3.6+ syntax here, to use [f-strings](https://realpython.com/python-f-strings/):
```suggestion
        f"{bucket_url}/{filename}",
```

2021-07-23 14:46 UTC, mrakitin commented on zenodo_uploader.py
> +r = requests.post('https://sandbox.zenodo.org/api/deposit/depositions', params=params, json={}, headers=headers)
Why not to use https://pypi.org/project/pyzenodo3/ here?
Also, I don't see how the metadata about the package is uploaded. I remember it was possible to do via a special parameter file...

2021-07-23 14:46 UTC, mrakitin commented on runner.sh.j2
> +read -p "To how many repositories would you like to upload the Docker image? (enter a numerical value from 0 - 3) " VALUE
We'd like to avoid interactive inputs. Could you please handle it via config .yml files? A dedicated parameter can be added there to where to upload, such as:
```yaml
docker_upload:
  - quay
  - dockerhub
  - ghcr
```

2021-07-23 14:46 UTC, mrakitin commented on runner.sh.j2
> +{% endfor %}
I suggest reworking it to exclude the jinja conditions, and rather use the .yml config files as input.

2021-07-23 14:46 UTC, mrakitin commented on runner.sh.j2
> +{% endif %}
Same comment as above - use config files to manage that part.

2021-07-23 14:49 UTC, mrakitin commented
I updated the PR body with the checklist:
![image](https://user-images.githubusercontent.com/13209176/126799750-27684b0b-de60-46f3-bf94-0494375192ca.png)

2021-07-23 18:56 UTC, johngedell commented on zenodo_uploader.py
> +ACCESS_TOKEN = input("Enter Access Token: ")
Done.

2021-07-23 18:56 UTC, johngedell commented on zenodo_uploader.py
> +        "%s/%s" % (bucket_url, filename),
Done.

2021-07-25 18:31 UTC, mrakitin reviewed
I spotted a couple of issues with the new addition to the Zenodo uploader code. Please use the "Commit suggestion" button(s) to commit the suggested changes, and then go `git pull` on your local clone.

2021-07-25 18:31 UTC, mrakitin commented on zenodo_uploader.py
> +        "f"(bucket_url, filename),
That's the correct syntax. Please read the docs about Python f-strings I posted earlier.
```suggestion
        f"{bucket_url}/{filename}",
```

2021-07-25 18:31 UTC, mrakitin commented on zenodo_uploader.py
> +os.getenv('ZENODO_ACCESS_TOKEN: ')
```suggestion
ACCESS_TOKEN = os.getenv('ZENODO_ACCESS_TOKEN')
if ACCESS_TOKEN is None:
    raise RuntimeError("ZENODO_ACCESS_TOKEN variable is not provided. "
                       "Please add it to the environment variables or pass it to the script.")
```

2021-07-26 02:05 UTC, johngedell commented on runner.sh.j2
> +image="nsls2-analysis-2021-1.2"
Done.

2021-07-26 02:05 UTC, johngedell commented on zenodo_uploader.py
> +    )
Done.

2021-07-26 02:05 UTC, johngedell commented on zenodo_uploader.py
> +r = requests.post('https://sandbox.zenodo.org/api/deposit/depositions', params=params, json={}, headers=headers)
Done.

2021-07-26 02:06 UTC, johngedell commented on runner.sh.j2
> +read -p "To how many repositories would you like to upload the Docker image? (enter a numerical value from 0 - 3) " VALUE
Interactive input avoided.

2021-07-26 02:07 UTC, johngedell commented on runner.sh.j2
> +{% endfor %}
Okay. I missed this when I was initially created the files. I will add this on my list of changes to make and leave unresolved.

2021-07-26 02:10 UTC, johngedell commented on zenodo_uploader.py
> +        "f"(bucket_url, filename),
Sorry! I should have updated this sooner. I made significant changes to this file already.

2021-07-26 02:10 UTC, johngedell commented on zenodo_uploader.py
> +os.getenv('ZENODO_ACCESS_TOKEN: ')
Yes, I made this change.

2021-07-27 00:01 UTC, johngedell commented on zenodo_uploader.py
> +path = input("Enter file path as '/path/to/my-file.zip': ")
Completed.

2021-07-27 14:37 UTC, mrakitin requested changes
@johngedell, here is my review. I did not see the items that you mentioned yesterday (such as moving `runner.sh` from `conda/` to the top of the dir, moving all template .j2 files into the `templates` directory, etc.)

Please address my comments, and add the discussed changes.

2021-07-27 14:37 UTC, mrakitin commented on conda/Dockerfile.j2
> +ENV OMPI_MCA_opal_cuda_support=true
I wonder to see what happens if we comment it out.

2021-07-27 14:37 UTC, mrakitin commented on conda/Dockerfile.j2
> +    conda create -n ${env_name} ${channels} --override-channels -y python=${python_version} conda-pack ${pkg_name} ${extra_packages} && \
We decided to create the environment with `-p /opt/conda_envs/${env_name}` instead of `-n ${env_name}`. Could you please update here accordingly?

2021-07-27 14:37 UTC, mrakitin commented on conda/Dockerfile.j2
> +COPY export.sh /home/conda/
Do we actually need it? It will be mounted by `runner.sh` and we don't need it as a part of the Docker image.

2021-07-27 14:37 UTC, mrakitin commented on conda/render.py
> +        f.write(text)
This file should be moved to the root of the repo, so that we could see actual changes with smaller diffs.

2021-07-27 14:37 UTC, mrakitin commented on conda/runner.sh.j2
> +export zenodo_upload_file_path=${env_name}.tar.gz
These three parameters should come from the config yaml files.

2021-07-27 14:37 UTC, mrakitin commented on conda/runner.sh.j2
> +docker run -ti --name temp ${env_name}:${timestamp} bash -l /home/conda/export.sh
So, here you'd mount the current directory with `-v $PWD:<your target>` and run the exporting script from there.

2021-07-27 14:37 UTC, mrakitin commented on conda/runner.sh.j2
> +docker rm -f temp
I don't understand why we need these lines. What's the motivation?

2021-07-27 14:37 UTC, mrakitin commented on conda/runner.sh.j2
> +{% for key in os.getenv("docker_upload").split(";") %}
Again, we'd like to get this variable from the config yaml files.

2021-07-27 14:37 UTC, mrakitin commented on conda/runner.sh.j2
> +{% if os.getenv("zenodo_upload") == "yes" %}
Get it from config yaml file.

2021-07-27 14:37 UTC, mrakitin commented on conda/zenodo_uploader.py
> +    print("Upload Done!")
Please move this file to the top dir of the repo.

2021-07-27 14:37 UTC, mrakitin commented on conda/zenodo_uploader.py
> +            )
Indentation is not right. It should be 4 blank spaces, not 8.

2021-07-27 14:37 UTC, mrakitin commented on conda/zenodo_uploader.py
> +                base_url="https://sandbox.zenodo.org/api/",
The base url should be passed as a keyword argument to the function, with the default to https://sandbox.zenodo.org/api/.

2021-07-27 14:37 UTC, mrakitin commented on conda/zenodo_uploader.py
> +                metafn=Path(""),
This part seems to be needed in general, to provide the metadata on uploading. But let's keep it empty for now - we will work on figuring it out once the uploading works and performs well.

2021-07-27 14:37 UTC, mrakitin commented on conda/zenodo_uploader.py
> +        "-f", "--file", dest="file_name_to_upload", help="the input config file"
The description should be corrected to mention it's the file to upload.

2021-07-27 14:37 UTC, mrakitin commented on conda/zenodo_uploader.py
> +    print("Upload Done!")
The print needs to have some resulting information, such as the full URL to where it was uploaded.

2021-07-27 15:33 UTC, johngedell commented on conda/zenodo_uploader.py
> +    print("Upload Done!")
Completed.

2021-07-27 15:51 UTC, johngedell commented on conda/export.sh
> +#while read requirement;do conda install --yes ${channels} --override-channels ${requirement};done < /requirements.txt
Removed.

2021-07-27 15:56 UTC, johngedell commented on conda/Dockerfile.j2
> +    conda config --set allow_conda_downgrades true && \
Done.

2021-07-27 15:58 UTC, johngedell commented on conda/Dockerfile.j2
> +RUN bash -lc "conda activate {{env_name}} && conda remove perl --force -y || echo Perl not found"
Changed.

2021-07-27 16:01 UTC, johngedell commented on conda/render.py
> +import argparse
Not sure what you mean here. That statement only shows up once on my end.

2021-07-27 16:02 UTC, johngedell commented on conda/render.py
> +            f.write(text)
I placed this file in the root directory.

2021-07-27 16:03 UTC, johngedell commented on conda/runner.sh.j2
> +
Completed.

2021-07-27 16:07 UTC, johngedell commented on conda/runner.sh.j2
> +docker rm -f temp
I removed the last 2 lines in this block.

2021-07-27 16:21 UTC, johngedell commented on conda/export.sh
> +conda env export -n ${env_name} -f ${env_name}.yml ${channels} --override-channels
Changed.

2021-07-27 16:41 UTC, johngedell commented on conda/Dockerfile.j2
> +ENV OMPI_MCA_opal_cuda_support=true
It doesn't change anything (just removes a notification). So I just removed this line.

2021-07-27 17:06 UTC, johngedell commented on conda/Dockerfile.j2
> +    conda init "bash"
Changed without issue.

2021-07-27 17:29 UTC, johngedell commented on conda/Dockerfile.j2
> +FROM {{os.getenv("docker_image")}} as build
Yes. Changed.

2021-07-27 17:29 UTC, johngedell commented on conda/Dockerfile.j2
> +ENV PATH="opt/conda/bin/:$PATH"
Updated.

2021-07-27 18:07 UTC, johngedell commented on conda/render.py
> +        f.write(text)
Completed.

2021-07-27 19:35 UTC, johngedell commented on conda/runner.sh.j2
> +docker run -ti --name temp ${env_name}:${timestamp} bash -l /home/conda/export.sh
I initially tried this, but it kept producing an error. I couldn't get the files to build with this command. So that's why I changed it. I can try to change it back, but it will take time.

2021-07-27 20:06 UTC, johngedell commented on conda/Dockerfile.j2
> +COPY export.sh /home/conda/
I am having trouble getting this to run without this command. So for now, I'd prefer to leave it in.

2021-07-27 20:12 UTC, johngedell commented on conda/zenodo_uploader.py
> +                base_url="https://sandbox.zenodo.org/api/",
Updated.

2021-07-27 20:13 UTC, johngedell commented on conda/zenodo_uploader.py
> +                metafn=Path(""),
Done.

2021-07-27 20:14 UTC, johngedell commented on conda/zenodo_uploader.py
> +            )
Fixed.

2021-07-27 20:16 UTC, johngedell commented on conda/zenodo_uploader.py
> +        "-f", "--file", dest="file_name_to_upload", help="the input config file"
Fixed.

2021-07-27 20:37 UTC, johngedell commented on conda/runner.sh.j2
> +{% if os.getenv("zenodo_upload") == "yes" %}
Done

2021-07-27 20:37 UTC, johngedell commented on conda/runner.sh.j2
> +{% for key in os.getenv("docker_upload").split(";") %}
Done

2021-07-27 20:37 UTC, johngedell commented on conda/runner.sh.j2
> +export zenodo_upload_file_path=${env_name}.tar.gz
Done

2021-07-27 20:38 UTC, johngedell commented on conda/runner.sh.j2
> +rm temp.yml
Done.

2021-07-28 01:51 UTC, mrakitin approved these changes
I am going to merge this PR now, and Zenodo uploading features can be added in subsequent PRs.

2021-07-28 01:51 UTC, merged

2021-07-30 04:24 UTC, mrakitin commented
The result for the third task is demonstrated in #13 and #11.

2021-07-30 04:26 UTC, mrakitin commented
The result for the first task is demonstrated in #11 and #9 (here, implemented via https://github.com/NSLS-II/conda-pack-template/pull/9/commits/b3dc5f1d7084a778d69019f9736b75601949f57b).